
# information about the dataset 
# always check for the column data types
# it defines the struture of the dataset
# it used to validate the dataset



columns:  # column names
  longitude: float
  latitude: float
  housing_median_age: float
  total_rooms: float
  total_bedrooms: float
  population: float
  households: float
  median_income: float
  median_house_value: float
  ocean_proximity: category

numerical_columns: # numerical column
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income



categorical_columns: # categorical column
  - ocean_proximity




target_column: median_house_value

domain_value:  # acceptable values in the categorical column
  ocean_proximity:
    - <1H OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN

